proxy:
    image: jwilder/nginx-proxy
    container_name: newspark_proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./containers/proxy/certs:/etc/nginx/certs

cleaner:
    build: ../poc-lsa-model
    container_name: cleaner
    environment:
        - VIRTUAL_HOST=cleaner.newspark.local
    volumes:
        - ../poc-lsa-model:/opt/newspark
    links:
        - mongo:mongo.newspark.local

mongo:
    image: mongo:3.2.8
    container_name: mongo_database
    environment: 
        - VIRTUAL_HOST=mongo.newspark.local
        - VIRTUAL_PORT=27017
    ports:
        - 27017:27017
    volumes:
        - ./tmp/mongo:/data/db
        - ./containers/mongo:/opt/defaults

scrapper:
    build: ../Scrappers
    container_name: scrapper
    environment: 
        - VIRTUAL_HOST=scrapper.newspark.local
    volumes:
        - ../Scrappers:/opt/newspark
    links:
        - mongo:mongo.newspark.local

api:
    build: ../newspark-backend
    container_name: api
    environment:
        - VIRTUAL_HOST=api.newspark.local
    ports:
        - 8080:8080
    volumes:
        - ../newspark-backend:/opt/newspark
    links:
        - mongo:mongo.newspark.local

front:
    build: ../newspark-frontend
    container_name: front
    environment:
        - VIRTUAL_HOST=front.newspark.local
    ports:
        - 80:80
    volumes:
        - ../newspark-frontend:/opt/newspark
